server:
  port: ${APP_PORT:8082}
  error:
    include-message: always
    include-binding-errors: always
app:
  environment: development
  core:
    url: ${CORE_URL:#{null}}
  cors:
    allowedOrigins: ${CORS_ALLOWED_HOSTS:*}
    allowedMethods: ${CORS_ALLOWED_HOSTS:*}
  local:
    storage:
      path: ${LOCAL_STORAGE_PATH:/tmp/}
spring:
  application:
    name: CurbeeService
springdoc:
  swagger-ui:
    query-config-enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  packagesToScan: com.james.curbee.controller
logging:
  level:
    org.springframework.web: "info"
